version: '3'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWWORD: password123
      POSTGRES_DB: main
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  redis:
    image: redis:5-alpine
    ports: [6379]

  fpm:
    build: ./docker/fpm
    user: 1000:1000
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    expose:
      - 9000
    links:
      - db
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - fpm
